on damage:
    wait 1 tick
    damage cause is attack
    event is not cancelled
    delete victim's velocity
    if (y of victim's velocity) < 2:
        if victim is on the ground:
            set y of victim's velocity to 0.4
            push victim in attacker's horizontal direction with force 0.5
        else:
            set y of victim's velocity to 0.3
            push victim in attacker's horizontal direction with force 0.3